spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://${MYSQL_DATASOURCE_HOST}:${MYSQL_DATASOURCE_PORT}/${MYSQL_DATASOURCE_DATABASE}
    username: ${MYSQL_DATASOURCE_USERNAME}
    password: ${MYSQL_DATASOURCE_PASSWORD}
    hikari:
      pool-name: MarketplaceNCMPool
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000      # 10 min
      max-lifetime: 1800000     # 30 min
      keepalive-time: 300000    # 5 min
      connection-timeout: 30000
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false  # ISO-8601
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: false
        jdbc:
          time_zone: UTC
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
jwt:
  secret: ${SECRET_KEY}
  expiration: ${EXPIRATION_TIME}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    version: 0.0.1
meta:
  credentials-key-b64: WC+JNalt5w6hkgPM+kVTX6qcAq8EOuy+rcMyCYhaXng=
do:
  spaces:
    access-key: ${DIGITAL_OCEAN_ACCESS_KEY}
    secret-key: ${DIGITAL_OCEAN_SECRET_KEY}
    region: ${DIGITAL_OCEAN_REGION}
    bucket-name: ${DIGITAL_OCEAN_BUCKET}
client:
  mercado-pago:
    url: https://api.mercadopago.com
    access-token: ${ACCESS_TOKEN}
    public-key: ${PUBLIC_KEY}
    plan:
      reference: ENTERPRISE_STANDART
      reason: Plano Empresarial Mensal
#      amount: 499
      amount: 1
gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite-preview-09-2025:generateContent"
    key: ${GEMINI_API_KEY}
quickin:
  api:
    url: "https://api.quickin.io"
    token: ${QUICKIN_TOKEN}
    account-id: ${QUICKIN_ACCOUNT_ID}
    company-id: ${QUICKIN_COMPANY_ID}
    candidatura-id: ${QUICKIN_CANDIDATURA_ID}
stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY} # Pega da vari√°vel de ambiente
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  price-id: ${STRIPE_PRICE_ID}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  candidate:
    price-id: ${STRIPE_CANDIDATE_PRICE_ID}
myapp:
  mail:
    from: ${VERIFIED_EMAIL}
linkedin:
  client-id: ${LINKEDIN_CLIENT_ID}
  client-secret: ${LINKEDIN_CLIENT_SECRET}
  redirect-uri: "http://marketplace.ncmconsultoria.com.br/br/auth/callback/linkedin" # URL do seu Front-end
  user-info-uri: "https://api.linkedin.com/v2/userinfo"